tarball removal on exit (with or w/o errors). Poll Review App creation status and accept review-app-creation-check-timeout and review-app-creation-check-sleep-time Action inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,6 +12,14 @@ inputs:
     description: "When true the .git/ folder is removed before creating the tar"
     required: false
     default: true
+  review-app-creation-check-timeout:
+    description: "Review App creation check timeout. Polling for the Review App creation up to timeout (in seconds)"
+    required: false
+    default: 3600
+  review-app-creation-check-sleep-time:
+    description: "While polling for the Review App creation it sleeps for this amount of time (in seconds), min 1 second to avoid tight loop and API calls consumption"
+    required: false
+    default: 10
 
 branding:
   icon: "play-circle"
@@ -27,6 +35,8 @@ runs:
         [[ "${{ inputs.heroku-api-key }}" ]] || { echo "heroku-api-key is required"; exit 1; }
         [[ "${{ inputs.heroku-pipeline-id }}" ]] || { echo "heroku-pipeline-id is required"; exit 1; }
         [[ "${{ inputs.remove-git-folder }}" != "true" && "${{ inputs.remove-git-folder }}" != "false" ]] && { echo "invalid value for remove-git-folder input. Expected 'true' or 'false'"; exit 1; }
+        [[ "${{ inputs.review-app-creation-check-timeout }}" =~ ^[0-9]+$ ]] || { echo "review-app-creation-check-timeout must be a number"; exit 1; }
+        [[ "${{ inputs.review-app-creation-check-sleep-time }}" =~ ^[0-9]+$ && -ge 1 ]] || { echo "review-app-creation-check-sleep-time must be a number >= 1"; exit 1; }
         echo "All inputs are valid"
 
     # this action must be preceeded by the actions/checkout to retrieve the source code
@@ -61,13 +71,29 @@ runs:
         URL=$(echo ${{ toJSON(env.SOURCE_ENDPOINT) }} | jq -er '.put')
         curl --fail-with-body $URL -X PUT -H 'Content-Type:' --data-binary @/tmp/source.tar.gz
 
+    # Now that the source code has been uploaded a trap EXIT is configured to catch both normal and error exit and remove the code, reducing its exposure time
+    # Currently the only way to wait for Review App creation is polling its status ("pending" or "creating" or "created" or "deleting" or "deleted" or "errored")
+    # Review App status check is retried up to 5 times with cURL to avoid aborting the polling phase due to transient errors
     - name: Create Review App
       if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened') }}
       shell: bash
       run: |
         echo "Create Review App"
+
+        trap tarball_cleanup EXIT
+
+        tarball_cleanup() {
+            local exit_code=$?
+            
+            echo "Exiting occurred with exit code: $exit_code - removing the source code tarball ..."
+            URL=$(echo ${{ toJSON(env.SOURCE_ENDPOINT) }} | jq -er '.put')
+            curl --fail-with-body $URL -X PUT -H 'Content-Type:' --data-binary ""
+            
+            exit $exit_code
+        }
+
         SOURCE_GET_URL=$(echo ${{ toJSON(env.SOURCE_ENDPOINT) }} | jq -er '.get')        
-        curl --fail-with-body -X POST https://api.heroku.com/review-apps \
+        REVIEW_APP_ID=$(curl --fail-with-body -X POST https://api.heroku.com/review-apps \
         -d '{"source_blob":{"url":"'"$SOURCE_GET_URL"'", "version": "'"${GITHUB_SHA::7}"'"},
         "pipeline":"'"${{ inputs.heroku-pipeline-id }}"'",
         "pr_number":${{ github.event.pull_request.number }},
@@ -75,7 +101,33 @@ runs:
         }' \
         -H "Accept: application/vnd.heroku+json; version=3" \
         -H "Content-Type: application/json" \
-        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}"
+        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}" | \
+        jq -er '.id')
+
+        echo "Waiting for Review App creation $REVIEW_APP_ID ..."
+        max_time="${{ review-app-creation-check-timeout }}"
+        start_time=$(date +%s)
+
+        while true; do
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))    
+            if [ "$elapsed_time" -ge "$max_time" ]; then
+                echo "Max execution time reached, breaking polling ..."
+                break   
+            fi
+
+            REVIEW_APP_STATUS=$(curl --retry 5 --fail-with-body "https://api.heroku.com/review-apps/REVIEW_APP_ID" \
+            -H "Accept: application/vnd.heroku+json; version=3" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ inputs.heroku-api-key }}" | \
+            jq -er '.status')
+
+            [[ "$REVIEW_APP_STATUS" == "created" ]] && { echo "Review App created successfully" ; exit 0; }
+            [[ "$REVIEW_APP_STATUS" == "errored" ]] && { echo "Review App creation completed with errors" ; exit 1; }
+
+            echo "Review App creation still in progress, waiting ${{ review-app-creation-check-sleep-time }} seconds ..."
+            sleep "${{ review-app-creation-check-sleep-time }}"
+        done
 
     - name: Delete Review App
       if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
