debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,9 +24,9 @@ runs:
       shell: bash
       run: |
         echo "Validating inputs ..."
-        [[ "${{ inputs.heroku-api-key }}" ]] || { echo "heroku-api-key is required" ; exit 1; }
-        [[ "${{ inputs.heroku-pipeline-id }}" ]] || { echo "heroku-pipeline-id is required" ; exit 1; }
-        [[ "${{ inputs.remove-git-folder }}" != "true" && "${{ inputs.remove-git-folder }}" != "false" ]] && { echo "invalid value for remove-git-folder input. Expected 'true' or 'false'" ; exit 1; }
+        [[ "${{ inputs.heroku-api-key }}" ]] || { echo "heroku-api-key is required"; exit 1; }
+        [[ "${{ inputs.heroku-pipeline-id }}" ]] || { echo "heroku-pipeline-id is required"; exit 1; }
+        [[ "${{ inputs.remove-git-folder }}" != "true" && "${{ inputs.remove-git-folder }}" != "false" ]] && { echo "invalid value for remove-git-folder input. Expected 'true' or 'false'"; exit 1; }
         echo "All inputs are valid"
 
     # this action must be preceeded by the actions/checkout to retrieve the source code
@@ -38,7 +38,6 @@ runs:
       if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
       shell: bash
       run: |
-        echo "Removing .git ..."
         [[ "${{ inputs.remove-git-folder }}" == "true" ]] && { echo "Removing .git folder ..." ; rm -rf .git; }
         echo "Compressing Source Code ..."
         find . -name "*" -print0 | xargs -0 tar -czvf /tmp/source.tar.gz
